spring.application.name=AuchanPortail
server.port=8081

spring.datasource.url=jdbc:h2:file:${user.home}/.auchan-portail/db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

app.jwt.secret=AuchanSenegalPortailSecretKey2026ChangeMeInProduction32CharsMin
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:4200
app.uploads.dir=${user.home}/.auchan-portail/logos
app.documents.dir=${user.home}/.auchan-portail/documents
